import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MuiThemeProvider from '@/context/MuiThemeProvider';
import { CssBaseline } from '@mui/material';
import SnackBarProvider from '@/context/SnackBarProvicer';
import ReactQueryClientProvider from '@/context/ReactQueryClientProvider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import CommonLayout from '@/components/commonLayout/CommonLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <CssBaseline />
          <MuiThemeProvider>
            <SnackBarProvider>
              <ReactQueryClientProvider>
                <CommonLayout>{children}</CommonLayout>
              </ReactQueryClientProvider>
            </SnackBarProvider>
          </MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
