export const MONTH_PURCHASE = 'MONTH_PURCHASE';
export const TODAY_PURCHASE = 'TODAY_PURCHASE';

export const MONTH_PRODUCT_PURCHASE = 'MONTH_PRODUCT_PURCHASE';
export const TODAY_PRODUCT_PURCHASE = 'TODAY_PRODUCT_PURCHASE';

export const MONTH_CLIENT_PURCHASE = 'MONTH_CLIENT_PURCHASE';
export const TODAY_CLIENT_PURCHASE = 'TODAY_CLIENT_PURCHASE';

export const VISIT_CLIENT_PURCHASE = 'VISIT_CLIENT_PURCHASE';
